# Feature Engineering

## Lesson 4 - Clustering with K-Means grouping

In [16]:
from matplotlib import pyplot as plt
from sklearn.cluster import KMeans
from sklearn.model_selection import cross_val_score
from xgboost import XGBRegressor

import pandas as pd
import numpy as np
import seaborn as sns

In [17]:
# Set Matplotlib defaults
plt.rc("figure", autolayout=True)
plt.rc(
    "axes",
    labelweight="bold",
    labelsize="large",
    titleweight="bold",
    titlesize=14,
    titlepad=10,
)


def score_dataset(X, y, model=XGBRegressor()):
    # Label encoding for categoricals
    for colname in X.select_dtypes(["category", "object"]):
        X[colname], _ = X[colname].factorize()
    # Metric for Housing competition is RMSLE (Root Mean Squared Log Error)
    score = cross_val_score(
        model, X, y, cv=5, scoring="neg_mean_squared_log_error",
    )
    score = -1 * score.mean()
    score = np.sqrt(score)
    return score


# Prepare data
df = pd.read_csv("../../resources/ames.csv")

### Exploring Clustering with Housing Data

In [18]:
housing_data = pd.read_csv('../../resources/housing.csv')
housing_data.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [19]:
X = housing_data.loc[:, ['MedInc', 'Latitude', 'Longitude']]
X.head()

   MedInc  Latitude  Longitude
0  8.3252     37.88    -122.23
1  8.3014     37.86    -122.22
2  7.2574     37.85    -122.24
3  5.6431     37.85    -122.25
4  3.8462     37.85    -122.25

#### Creating Clusters using KMeans Algorithm

In [20]:
kmeans = KMeans(n_clusters=6, n_init=10, random_state=0)
X['Cluster'] = kmeans.fit_predict(X)
X['Cluster'] = X['Cluster'].astype("category")
X.head()

.venv/lib/python3.12/site-packages/sklearn/utils/extmath.py:229: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
.venv/lib/python3.12/site-packages/sklearn/utils/extmath.py:229: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
.venv/lib/python3.12/site-packages/sklearn/utils/extmath.py:229: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
.venv/lib/python3.12/site-packages/sklearn/cluster/_kmeans.py:243: RuntimeWarning: divide by zero encountered in matmul
  current_pot = closest_dist_sq @ sample_weight
.venv/lib/python3.12/site-packages/sklearn/cluster/_kmeans.py:243: RuntimeWarning: overflow encountered in matmul
  current_pot = closest_dist_sq @ sample_weight
.venv/lib/python3.12/site-packages/sklearn/cluster/_kmeans.py:243: RuntimeWarning: invalid value encountered in matmul
  current_pot = closest_dist_sq @ sample_weight

   MedInc  Latitude  Longitude Cluster
0  8.3252     37.88    -122.23       5
1  8.3014     37.86    -122.22       5
2  7.2574     37.85    -122.24       5
3  5.6431     37.85    -122.25       5
4  3.8462     37.85    -122.25       1

#### Visualising Clusters using relplot

In [ ]:
sns.relplot(x="Latitude", y="Longitude", hue="Cluster", data=X, palette="viridis")

In [21]:
X_cd = kmeans.fit_transform(X)

.venv/lib/python3.12/site-packages/sklearn/utils/extmath.py:229: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
.venv/lib/python3.12/site-packages/sklearn/utils/extmath.py:229: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
.venv/lib/python3.12/site-packages/sklearn/utils/extmath.py:229: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
.venv/lib/python3.12/site-packages/sklearn/cluster/_kmeans.py:243: RuntimeWarning: divide by zero encountered in matmul
  current_pot = closest_dist_sq @ sample_weight
.venv/lib/python3.12/site-packages/sklearn/cluster/_kmeans.py:243: RuntimeWarning: overflow encountered in matmul
  current_pot = closest_dist_sq @ sample_weight
.venv/lib/python3.12/site-packages/sklearn/cluster/_kmeans.py:243: RuntimeWarning: invalid value encountered in matmul
  current_pot = closest_dist_sq @ sample_weight
.venv/lib/python3.12/site-packages/sklearn/utils/extmath.py:229: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
.venv/lib/python3.12/site-packages/sklearn/utils/extmath.py:229: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
.venv/lib/python3.12/site-packages/sklearn/utils/extmath.py:229: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b

In [22]:
cols = [f"Centroid {i}" for i in range(X_cd.shape[1])]
print(cols)

['Centroid 0', 'Centroid 1', 'Centroid 2', 'Centroid 3', 'Centroid 4', 'Centroid 5']

In [23]:
X_cd = pd.DataFrame(X_cd, columns=cols)
X = X.join(X_cd)
X.head()

,MedInc,Latitude,Longitude,Cluster,Centroid 0,Centroid 1,Centroid 2,Centroid 3,Centroid 4,Centroid 5
0,8.3252,37.88,-122.23,5,8.649455,6.826420,5.247102,6.512822,8.180195,2.821048
1,8.3014,37.86,-122.22,5,8.619931,6.808180,5.242286,6.482874,8.156979,2.795311
2,7.2574,37.85,-122.24,5,8.007420,6.002302,5.836123,5.605190,7.862507,1.762806
3,5.6431,37.85,-122.25,5,7.252798,4.932203,6.963577,4.387934,7.665779,0.339788
4,3.8462,37.85,-122.25,1,6.149472,1.193238,8.403526,4.448300,6.115513,4.348375