# Feature Engineering - Creating Features

## Lesson 3 - Creating Features

#### Objectives:
1. Common Transformations
2. Reasearch problem domain to acquire domain knowledge
3. Use Data Visualization to gain insights

---

### Mathematical Transformations:

In [26]:
from IPython.display import display

import pandas as pd
import numpy as np

In [8]:
autos = pd.read_csv('../../resources/autos.csv')
autos.head()

,symboling,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,alfa-romero,gas,std,2,convertible,rwd,front,88.6,168.8,...,130,mpfi,3.47,2.68,9,111,5000,21,27,13495
1,3,alfa-romero,gas,std,2,convertible,rwd,front,88.6,168.8,...,130,mpfi,3.47,2.68,9,111,5000,21,27,16500
2,1,alfa-romero,gas,std,2,hatchback,rwd,front,94.5,171.2,...,152,mpfi,2.68,3.47,9,154,5000,19,26,16500
3,2,audi,gas,std,4,sedan,fwd,front,99.8,176.6,...,109,mpfi,3.19,3.40,10,102,5500,24,30,13950
4,2,audi,gas,std,4,sedan,4wd,front,99.4,176.6,...,136,mpfi,3.19,3.40,8,115,5500,18,22,17450

In [9]:
columns = [col for col in autos.columns]
print(columns)

['symboling', 'make', 'fuel_type', 'aspiration', 'num_of_doors', 'body_style', 'drive_wheels', 'engine_location', 'wheel_base', 'length', 'width', 'height', 'curb_weight', 'engine_type', 'num_of_cylinders', 'engine_size', 'fuel_system', 'bore', 'stroke', 'compression_ratio', 'horsepower', 'peak_rpm', 'city_mpg', 'highway_mpg', 'price']

In [10]:
autos[["stroke", "bore"]].head()

   stroke  bore
0    2.68  3.47
1    2.68  3.47
2    3.47  2.68
3    3.40  3.19
4    3.40  3.19

With pandas built-in functions, it's quite useful to create custom computed transformations that makes more meaningful features that contributes to machine learning

For example:
1. Calculating `stroke_ratio` from `stroke` and `bore` data
2. Calculating `displacement`, etc.

In [11]:
# Create a new feature by computing two existing features
autos['stroke_ratio'] = autos['stroke'] / autos['bore']

autos[['stroke', 'bore', 'stroke_ratio']].head()

   stroke  bore  stroke_ratio
0    2.68  3.47      0.772334
1    2.68  3.47      0.772334
2    3.47  2.68      1.294776
3    3.40  3.19      1.065831
4    3.40  3.19      1.065831

In [14]:
# calculating displament
autos['displacement'] = (
    np.pi * ((0.5 * autos['bore']) ** 2) * autos['stroke'] * autos['num_of_cylinders']
)

autos['displacement'].head()

0    101.377976
1    101.377976
2    117.446531
3    108.695147
4    135.868934
Name: displacement, dtype: float64

### Counts

In [15]:
sample_data = {
    "amenity": [True, False, False, False],
    "bump": [False, False, False, False],
    "crossing": [True, True, False, False],
    "emergency": [False, False, False, True]
}

df = pd.DataFrame(sample_data)
df.head()

   amenity   bump  crossing  emergency
0     True  False      True      False
1    False  False      True      False
2    False  False     False      False
3    False  False     False       True

#### Computed counts by Axis
- **0** - Columns
- **1** - Rows

In [16]:
df['overview'] = df.sum(axis=1)
df.head()

   amenity   bump  crossing  emergency  overview
0     True  False      True      False         2
1    False  False      True      False         1
2    False  False     False      False         0
3    False  False     False       True         1

In [20]:
df['valid'] = df.sum(axis=1).gt(1)
df.head()

   amenity   bump  crossing  emergency  overview  total  valid
0     True  False      True      False         2    NaN   True
1    False  False      True      False         1    NaN   True
2    False  False     False      False         0    NaN  False
3    False  False     False       True         1    NaN   True

#### Building Up & Breaking Down

In [21]:
policy = {
    "policy": ["corp l2", "corp l3", "corp l4", "corp l5", "per l1","per l2", "per l3", "per l4", "per l5"],
}
df = pd.DataFrame(policy)
df.head()

    policy
0  corp l2
1  corp l3
2  corp l4
3  corp l5
4   per l1

In [22]:
# split the policy column into two columns
df[['type', 'level']] = (
    df['policy'].str.split(' ', expand=True)
)
print(df)

    policy  type level
0  corp l2  corp    l2
1  corp l3  corp    l3
2  corp l4  corp    l4
3  corp l5  corp    l5
4   per l1   per    l1
5   per l2   per    l2
6   per l3   per    l3
7   per l4   per    l4
8   per l5   per    l5

In [23]:
# merge two columns' values into one column
df['access'] = (
    (df['type'] + '_' + df['level']).str.upper()
)
df.head()

    policy  type level   access
0  corp l2  corp    l2  CORP_L2
1  corp l3  corp    l3  CORP_L3
2  corp l4  corp    l4  CORP_L4
3  corp l5  corp    l5  CORP_L5
4   per l1   per    l1   PER_L1

### Group Transforms

In [29]:
income_by_states = {
    "country": ["Australia", "Australia", "Australia", "Australia", "Australia", "Australia", "Australia", "Australia"],
    "state": ["ACT", "NT", "WA", "NSW", "VIC", "QLD", "SA", "TAS"],
    "income": [75643, 66831, 62207, 58909, 57907, 56708, 55782, 53479]
}
df = pd.DataFrame(income_by_states)
df.head()

     country state  income
0  Australia   ACT   75643
1  Australia    NT   66831
2  Australia    WA   62207
3  Australia   NSW   58909
4  Australia   VIC   57907

In [30]:
df['avg_income'] = (
    df.groupby('country')
    ['income']
    .transform('mean')
)

display(df)

     country state  income  avg_income
0  Australia   ACT   75643    60933.25
1  Australia    NT   66831    60933.25
2  Australia    WA   62207    60933.25
3  Australia   NSW   58909    60933.25
4  Australia   VIC   57907    60933.25
5  Australia   QLD   56708    60933.25
6  Australia    SA   55782    60933.25
7  Australia   TAS   53479    60933.25

In [31]:
display(df['avg_income'].unique())

array([60933.25])

In [32]:
attendance = {
    "check_in": ["in", "in", "in", "out", "in", "out", "out", "out", "in" ]
}
df = pd.DataFrame(attendance)
display(df)

  check_in
0       in
1       in
2       in
3      out
4       in
5      out
6      out
7      out
8       in

In [34]:
df['check_in_count'] = (
    df.groupby('check_in')
    ['check_in']
    .transform('count')
)
print(df)

  check_in  check_in_count
0       in               5
1       in               5
2       in               5
3      out               4
4       in               5
5      out               4
6      out               4
7      out               4
8       in               5

In [37]:
df['check_in_frequency'] = (
    df['check_in_count'] / df['check_in'].count()
)
display(df)

  check_in  check_in_count  check_in_frequency
0       in               5            0.555556
1       in               5            0.555556
2       in               5            0.555556
3      out               4            0.444444
4       in               5            0.555556
5      out               4            0.444444
6      out               4            0.444444
7      out               4            0.444444
8       in               5            0.555556

In [42]:
df['check_in_factorize'], _ = df['check_in_count'].factorize()
display(df)

  check_in  check_in_count  check_in_frequency  check_in_factorize
0       in               5            0.555556                   0
1       in               5            0.555556                   0
2       in               5            0.555556                   0
3      out               4            0.444444                   1
4       in               5            0.555556                   0
5      out               4            0.444444                   1
6      out               4            0.444444                   1
7      out               4            0.444444                   1
8       in               5            0.555556                   0

In [44]:
display(df.value_counts())

check_in  check_in_count  check_in_frequency  check_in_factorize
in        5               0.555556            0                     5
out       4               0.444444            1                     4
Name: count, dtype: int64

---

In [45]:
ames_data = pd.read_csv('../../resources/ames.csv')
X = ames_data.copy()
y = X.pop('SalePrice')

print("X\n"+ ("-" * 10))
display(X.head())

print("\ny\n" + ("-" * 10))
display(y.head())

X
----------

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YearSold,SaleType,SaleCondition
0,One_Story_1946_and_Newer_All_Styles,Residential_Low_Density,141.0,31770.0,Pave,No_Alley_Access,Slightly_Irregular,Lvl,AllPub,Corner,...,0.0,0.0,No_Pool,No_Fence,NaN,0.0,5,2010,WD,Normal
1,One_Story_1946_and_Newer_All_Styles,Residential_High_Density,80.0,11622.0,Pave,No_Alley_Access,Regular,Lvl,AllPub,Inside,...,120.0,0.0,No_Pool,Minimum_Privacy,NaN,0.0,6,2010,WD,Normal
2,One_Story_1946_and_Newer_All_Styles,Residential_Low_Density,81.0,14267.0,Pave,No_Alley_Access,Slightly_Irregular,Lvl,AllPub,Corner,...,0.0,0.0,No_Pool,No_Fence,Gar2,12500.0,6,2010,WD,Normal
3,One_Story_1946_and_Newer_All_Styles,Residential_Low_Density,93.0,11160.0,Pave,No_Alley_Access,Regular,Lvl,AllPub,Corner,...,0.0,0.0,No_Pool,No_Fence,NaN,0.0,4,2010,WD,Normal
4,Two_Story_1946_and_Newer,Residential_Low_Density,74.0,13830.0,Pave,No_Alley_Access,Slightly_Irregular,Lvl,AllPub,Inside,...,0.0,0.0,No_Pool,Minimum_Privacy,NaN,0.0,3,2010,WD,Normal

y
----------

0    215000
1    105000
2    172000
3    244000
4    189900
Name: SalePrice, dtype: int64

In [54]:
X['LivLotRatio'] = (X['GrLivArea'] / X['LotArea'])
X[['GrLivArea', 'LotArea', 'LivLotRatio']].head()

   GrLivArea  LotArea  LivLotRatio
0     1656.0  31770.0     0.052125
1      896.0  11622.0     0.077095
2     1329.0  14267.0     0.093152
3     2110.0  11160.0     0.189068
4     1629.0  13830.0     0.117787

In [55]:
X['Spaciousness'] = (X['FirstFlrSF'] + X['SecondFlrSF']) / X['TotRmsAbvGrd']
X[['FirstFlrSF', 'SecondFlrSF', 'TotRmsAbvGrd', 'Spaciousness']].head()

   FirstFlrSF  SecondFlrSF  TotRmsAbvGrd  Spaciousness
0      1656.0          0.0             7    236.571429
1       896.0          0.0             5    179.200000
2      1329.0          0.0             6    221.500000
3      2110.0          0.0             8    263.750000
4       928.0        701.0             6    271.500000

In [58]:
X['TotalOutsideSF'] = X['WoodDeckSF'] + X['OpenPorchSF'] + X['EnclosedPorch'] + X['Threeseasonporch'] + X['ScreenPorch']
X[['WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', 'Threeseasonporch', 'ScreenPorch', 'TotalOutsideSF']].head()

,WoodDeckSF,OpenPorchSF,EnclosedPorch,Threeseasonporch,ScreenPorch,TotalOutsideSF
0,210.0,62.0,0.0,0.0,0.0,272.0
1,140.0,0.0,0.0,0.0,120.0,260.0
2,393.0,36.0,0.0,0.0,0.0,429.0
3,0.0,0.0,0.0,0.0,0.0,0.0
4,212.0,34.0,0.0,0.0,0.0,246.0

In [60]:
X['BldgType'].value_counts()

BldgType
OneFam      2425
TwnhsE       233
Duplex       109
Twnhs        101
TwoFmCon      62
Name: count, dtype: int64

In [61]:
X_2 = pd.DataFrame()

X_2 = pd.get_dummies(X['BldgType'], prefix="Bldg")

X_2.head()

   Bldg_Duplex  Bldg_OneFam  Bldg_Twnhs  Bldg_TwnhsE  Bldg_TwoFmCon
0        False         True       False        False          False
1        False         True       False        False          False
2        False         True       False        False          False
3        False         True       False        False          False
4        False         True       False        False          False

In [62]:
X_2 = X_2.mul(X['GrLivArea'], axis=0)
X_2.head()

   Bldg_Duplex  Bldg_OneFam  Bldg_Twnhs  Bldg_TwnhsE  Bldg_TwoFmCon
0          0.0       1656.0         0.0          0.0            0.0
1          0.0        896.0         0.0          0.0            0.0
2          0.0       1329.0         0.0          0.0            0.0
3          0.0       2110.0         0.0          0.0            0.0
4          0.0       1629.0         0.0          0.0            0.0

In [80]:
X['PorchTypes'] = X[['WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', 'Threeseasonporch', 'ScreenPorch']].gt(0).sum(axis=1)

X[['WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', 'Threeseasonporch', 'ScreenPorch', 'PorchTypes']].head()

,WoodDeckSF,OpenPorchSF,EnclosedPorch,Threeseasonporch,ScreenPorch,PorchTypes
0,210.0,62.0,0.0,0.0,0.0,2
1,140.0,0.0,0.0,0.0,120.0,2
2,393.0,36.0,0.0,0.0,0.0,2
3,0.0,0.0,0.0,0.0,0.0,0
4,212.0,34.0,0.0,0.0,0.0,2

In [65]:
X.MSSubClass.unique()

<StringArray>
[      'One_Story_1946_and_Newer_All_Styles',
                  'Two_Story_1946_and_Newer',
              'One_Story_PUD_1946_and_Newer',
      'One_and_Half_Story_Finished_All_Ages',
                               'Split_Foyer',
              'Two_Story_PUD_1946_and_Newer',
                       'Split_or_Multilevel',
                  'One_Story_1945_and_Older',
                'Duplex_All_Styles_and_Ages',
 'Two_Family_conversion_All_Styles_and_Ages',
    'One_and_Half_Story_Unfinished_All_Ages',
                  'Two_Story_1945_and_Older',
               'Two_and_Half_Story_All_Ages',
    'One_Story_with_Finished_Attic_All_Ages',
          'PUD_Multilevel_Split_Level_Foyer',
           'One_and_Half_Story_PUD_All_Ages']
Length: 16, dtype: str

In [75]:
X['MSSubclass_Type'] = (X['MSSubClass'].str.split('_', n=1, expand=True))[0]

X[['MSSubClass', 'MSSubclass_Type']].head()

                            MSSubClass MSSubclass_Type
0  One_Story_1946_and_Newer_All_Styles             One
1  One_Story_1946_and_Newer_All_Styles             One
2  One_Story_1946_and_Newer_All_Styles             One
3  One_Story_1946_and_Newer_All_Styles             One
4             Two_Story_1946_and_Newer             Two

In [76]:
X['MedNhbdArea'] = (
    X.groupby('Neighborhood')
    ['GrLivArea']
    .transform('median')
)

X[['Neighborhood', 'GrLivArea', 'MedNhbdArea']].head()

  Neighborhood  GrLivArea  MedNhbdArea
0   North_Ames     1656.0       1200.0
1   North_Ames      896.0       1200.0
2   North_Ames     1329.0       1200.0
3   North_Ames     2110.0       1200.0
4      Gilbert     1629.0       1560.0

In [78]:
from sklearn.model_selection import cross_val_score
from xgboost import XGBRegressor

In [79]:
def score_dataset(X, y, model=XGBRegressor()):
    # Label encoding for categoricals
    for colname in X.select_dtypes(["category", "object"]):
        X[colname], _ = X[colname].factorize()
    # Metric for Housing competition is RMSLE (Root Mean Squared Log Error)
    score = cross_val_score(
        model, X, y, cv=5, scoring="neg_mean_squared_log_error",
    )
    score = -1 * score.mean()
    score = np.sqrt(score)
    return score

In [83]:
X_new = X.join([X_2])
X_new.columns

Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street', 'Alley',
       'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
       'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea',
       'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC',
       'CentralAir', 'Electrical', 'FirstFlrSF', 'SecondFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd',
       'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType', 'GarageFinish',
       'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond', 'PavedDrive',
       'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', 'Threeseasonporch',
       'ScreenPorch', 'PoolArea', 'PoolQC', 'Fence', 'MiscFeature', 'MiscVal',
       'MoSold', 'YearSold', 'SaleType', 'SaleCondition', 'LivLotRatio',
       'Spaciousness', 'TotalOutsideSF', 'PorchTypes', 'MSSubclass_Type',
       'MedNhbdArea', 'Bldg_Duplex', 'Bldg_OneFam', 'Bldg_Twnhs',
       'Bldg_TwnhsE', 'Bldg_TwoFmCon'],
      dtype='str')

In [84]:
score_dataset(X_new, y)

ipykernel_39219/1084380591.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for colname in X.select_dtypes(["category", "object"]):

np.float64(0.13955247956744776)